import { Applicant } from "./Shared";

export const MOCK_TEST_APPLICANTS: Applicant[] = [
  {
    id: "mock_1",
    name: "أحمد عبدالله",
    job: "مدير مشروع",
    rating: 95,
    status: "فوري",
    color: "emerald",
    phone: "0501234567",
    email: "ahmed@example.com",
    skills: ["إدارة المشاريع", "Scrum", "Agile", "التواصل الفعال"],
    aiSummary: "يمتلك خبرة واسعة تزيد عن 8 سنوات في إدارة المشاريع التقنية. أظهر قدرة استثنائية على قيادة الفرق وتحقيق الأهداف ضمن الميزانية والوقت المحددين. توصية نهائية: مرشح قوي جداً للقيادة.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "15,000 ريال",
    cv_file_url: "https://images.unsplash.com/photo-1586281380117-5a60ae2050cc?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=11",
    top_strengths: ["القيادة الاستراتيجية", "إدارة المخاطر"],
    top_weaknesses: ["يحتاج لخبرة أكثر في المشاريع المالية"]
  },
  {
    id: "mock_2",
    name: "سارة خالد",
    job: "مطور واجهات أمامية",
    rating: 88,
    status: "بعد شهر",
    color: "amber",
    phone: "0507654321",
    email: "sara.k@example.com",
    skills: ["React", "TypeScript", "Tailwind CSS", "UI/UX"],
    aiSummary: "مطور واجهات ممتاز مع اهتمام عالي بالتفاصيل وتجربة المستخدم. تمتلك معرض أعمال قوي. توصية نهائية: مناسبة جداً لفريق التطوير.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "12,000 ريال",
    cv_file_url: "https://images.unsplash.com/photo-1616587896813-f66100f98fb9?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=5",
    top_strengths: ["كتابة كود نظيف", "التفكير التصميمي"],
    top_weaknesses: ["خبرة محدودة في Backend"]
  },
  {
    id: "mock_3",
    name: "محمد العتيبي",
    job: "محلل بيانات",
    rating: 72,
    status: "فوري",
    color: "red",
    phone: "0555555555",
    email: "mohammad.o@example.com",
    skills: ["Python", "SQL", "Tableau", "Excel"],
    aiSummary: "محلل بيانات جيد ولكن خبرته تتركز أكثر في الأدوات التقليدية. يفتقر لبعض مهارات تحليل البيانات الضخمة (Big Data). توصية نهائية: مرشح احتياطي يحتاج لتدريب إضافي.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "9,000 ريال",
    cv_file_url: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=12",
    top_strengths: ["تحليل البيانات الإحصائية", "العمل تحت الضغط"],
    top_weaknesses: ["لا يجيد استخدام أدوات Big Data الحديثة"]
  },
  {
    id: "mock_4",
    name: "نورة الدوسري",
    job: "مصمم جرافيك",
    rating: 92,
    status: "فوري",
    color: "emerald",
    phone: "0533333333",
    email: "noura.d@example.com",
    skills: ["Photoshop", "Illustrator", "InDesign", "Branding"],
    aiSummary: "مصممة مبدعة جداً تمتلك ملف أعمال (Portfolio) غني بالتصاميم الحديثة والمبتكرة. تناسب بيئة العمل الإبداعية. توصية نهائية: توظيف مباشر لقسم التسويق.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "10,000 ريال",
    cv_file_url: "https://images.unsplash.com/photo-1586281380117-5a60ae2050cc?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=9",
    top_strengths: ["إبداع عالي", "سرعة الإنجاز"],
    top_weaknesses: ["قد تحتاج لبعض التوجيه في تصاميم واجهات الويب"]
  },
  {
    id: "mock_5",
    name: "عبدالرحمن الشمري",
    job: "مهندس شبكات",
    rating: 85,
    status: "بعد أسبوعين",
    color: "amber",
    phone: "0566666666",
    email: "abdulrahman.sh@example.com",
    skills: ["Cisco", "Routing", "Switching", "Firewalls"],
    aiSummary: "مهندس شبكات متمكن مع شهادات احترافية مثل CCNP. يمتلك خبرة في بناء البنى التحتية الآمنة. توصية نهائية: ممتاز ولكن يفضل اختباره عملياً في بيئة معقدة.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "14,000 ريال",
    cv_file_url: "https://images.unsplash.com/photo-1616587896813-f66100f98fb9?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=13",
    top_strengths: ["الشهادات الاحترافية", "استكشاف الأخطاء وإصلاحها"],
    top_weaknesses: ["مهارات تواصل متوسطة"]
  },
  {
    id: "mock_6",
    name: "ليلى المطيري",
    job: "مسؤول موارد بشرية",
    rating: 98,
    status: "فوري",
    color: "emerald",
    phone: "0544444444",
    email: "laila.m@example.com",
    skills: ["الاستقطاب", "إدارة المواهب", "شؤون الموظفين", "حل النزاعات"],
    aiSummary: "شخصية ديناميكية وخبرة تتجاوز 10 سنوات في قطاع الموارد البشرية. قادرة على بناء ثقافة عمل إيجابية. توصية نهائية: مرشحة مثالية لإدارة القسم.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "18,000 ريال",
    cv_file_url: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=20",
    top_strengths: ["الذكاء العاطفي", "القيادة"],
    top_weaknesses: ["تفويض المهام في بعض الأحيان"]
  },
  {
    id: "mock_7",
    name: "فيصل الحربي",
    job: "مطور تطبيقات هواتف",
    rating: 79,
    status: "فوري",
    color: "red",
    phone: "0599999999",
    email: "faisal.h@example.com",
    skills: ["Flutter", "Dart", "Firebase", "API Integration"],
    aiSummary: "مطور واعد بمهارات تقنية جيدة، لكن يفتقر لخبرة واسعة في نشر التطبيقات على المتاجر والتعامل مع التطبيقات الضخمة. توصية نهائية: يصلح كعضو فريق مبتدئ.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "8,000 ريال",
    cv_file_url: "https://images.unsplash.com/photo-1586281380117-5a60ae2050cc?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=14",
    top_strengths: ["شغف بالتعلم", "العمل الجماعي"],
    top_weaknesses: ["خبرة عملية محدودة في بيئة الإنتاج"]
  },
  {
    id: "mock_8",
    name: "ريم القحطاني",
    job: "أخصائي تسويق رقمي",
    rating: 89,
    status: "بعد شهر",
    color: "amber",
    phone: "0588888888",
    email: "reem.q@example.com",
    skills: ["SEO", "Google Ads", "Social Media", "Content Creation"],
    aiSummary: "أخصائية تسويق تتمتع بفهم عميق لسلوك المستهلك وتحليل الحملات الرقمية. حققت عوائد استثمار ممتازة في حملاتها السابقة. توصية نهائية: مناسبة لقيادة الحملات الإعلانية.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "11,000 ريال",
    cv_file_url: "https://images.unsplash.com/photo-1616587896813-f66100f98fb9?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=28",
    top_strengths: ["تحليل البيانات التسويقية", "إدارة الميزانيات"],
    top_weaknesses: ["تحتاج لتعلم بعض أدوات التصميم الأساسية"]
  },
  {
    id: "mock_9",
    name: "سعود الغامدي",
    job: "محاسب مالي",
    rating: 94,
    status: "فوري",
    color: "emerald",
    phone: "0511111111",
    email: "saud.g@example.com",
    skills: ["إعداد القوائم المالية", "التدقيق", "الزكاة والضرائب", "ERP"],
    aiSummary: "محاسب محترف ومسجل لدى الهيئة السعودية للمراجعين. دقته العالية والتزامه بالمعايير يجعله إضافة قيمة. توصية نهائية: مرشح قوي وموثوق للمهام المالية المعقدة.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "13,000 ريال",
    cv_file_url: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=15",
    top_strengths: ["الدقة المتناهية", "المعرفة العميقة بالقوانين الضريبية"],
    top_weaknesses: ["تفضيل العمل الفردي أحياناً"]
  },
  {
    id: "mock_10",
    name: "حصة المالك",
    job: "مدير مبيعات",
    rating: 91,
    status: "فوري",
    color: "emerald",
    phone: "0522222222",
    email: "hessa.m@example.com",
    skills: ["B2B Sales", "التفاوض", "إدارة علاقات العملاء (CRM)", "التخطيط الاستراتيجي"],
    aiSummary: "مديرة مبيعات استثنائية بسجل حافل في تحقيق وتجاوز المستهدفات البيعية (Targets). تمتلك مهارات تفاوض عالية وبناء علاقات قوية. توصية نهائية: خيار استراتيجي لتوسيع حصة السوق.",
    voiceEval: "",
    customAnswers: [],
    decision: "pending",
    expectedSalary: "20,000 ريال + عمولات",
    cv_file_url: "https://images.unsplash.com/photo-1586281380117-5a60ae2050cc?w=800&q=80",
    photoUrl: "https://i.pravatar.cc/150?img=32",
    top_strengths: ["مهارات الإقناع العالية", "تحفيز فريق المبيعات"],
    top_weaknesses: ["قد تكون متطلبة جداً مع فريقها"]
  }
];
